In [1]:
import json
import requests
import pandas as pd

In [3]:
# test = {"City": ["New+York", "Los+Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San+Antonio", "San+Diego", "Dallas", "San+Jose"], "State": ["NY", "CA", "IL", "TX", "AZ", "PA", "TX", "CA", "TX", "CA"]}
# test_df = pd.DataFrame(data=test)
# test_df
# url = f'https://public.opendatasoft.com/api/records/1.0/search/?dataset=us-zip-code-latitude-and-longitude&q=' + {city_state} + '&facet=state&facet=timezone&facet=dst'

city_list = []
state_list = []
zip_list = []
lat_list = []
lon_list = []


city_state = ["New+York%2C+NY", "Los+Angeles%2C+CA", "Chicago%2C+IL", "Houston%2C+TX", "Phoenix%2C+AZ", "Philadelphia%2C+PA", 
              "San+Antonio%2C+TX", "San+Diego%2C+CA", "Dallas%2C+TX", "San+Jose%2C+CA", "Austin%2C+TX", "Jacksonville%2C+FL", 
              "Fort+Worth%2C+TX", "Columbus%2C+OH", "Charlotte%2C+NC", "San+Francisco%2C+CA","Indianapolis%2C+IN",
             "Seattle%2C+WA", "Denver%2C+CO","Washington%2C+DC",]
url1 = 'https://public.opendatasoft.com/api/records/1.0/search/?dataset=us-zip-code-latitude-and-longitude&row=600&q='
url2 = '&facet=state&facet=timezone&facet=dst'

for city in city_state:
    
    city_number = 0
    
    response = requests.get(url1 + city + url2).json()
    
#     for records in response['records'][0]['recordid']:
    
#         city_list.append(response['records'][0]['fields']['city'])
#         state_list.append(response['records'][0]['fields']['state'])
#         zip_list.append(response['records'][0]['fields']['zip'])
#         lat_list.append(response['records'][0]['fields']['latitude'])
#         lon_list.append(response['records'][0]['fields']['longitude'])
    
# response['records'][0].keys()

# response['records'][0][''.keys()

# zip_list
    for record in response['records']:
        
        try:
            print(response['records'][city_number]['fields']['zip'])
            city_number = city_number + 1
        except:
            continue

10170
10275
10015
10032
10265
10179
10158
10045
10018
10016
90004
90019
90058
90185
90066
90039
90070
90094
90079
90091
60644
60629
60692
60639
60636
60657
60618
60677
60628
60608
77014
77221
77022
77031
77094
77055
77222
77098
77235
77281
85032
85051
85076
85038
85020
85004
85045
85001
85031
85085
19196
19127
19109
19175
19092
19129
19191
19124
19183
19185
78211
78278
78256
78270
78283
78218
78232
78236
78299
78203
92147
92186
92135
92133
92166
92113
92106
92160
92109
92168
75287
75336
75239
75233
75320
75380
75277
75227
75353
75264
95158
95129
95154
95190
95131
95160
95155
95108
95115
95159
78748
73301
78789
78773
78709
78733
78723
78708
78731
78721
32216
32238
32218
32226
32254
32223
32219
32228
32211
32256
76140
76107
76179
76113
76150
76115
76106
76101
76132
76148
43224
43287
43201
43214
43202
43272
43266
43232
43284
43215
28296
28266
28231
28226
28202
28255
28221
28228
28227
28258
94168
94188
94105
94161
94122
94141
94110
94166
94126
94101
46278
46230
46217
46268
46226
46206
46207
46254
46229
46266
98184
98190
98195
98144
98133
98115
98119
98146
98198
98185
80292
80241
80219
80237
80209
80244
80274
80271
80211
80223
20571
20456
20505
20229
20590
20375
20340
20207
20071
20059